// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	LoginPostOperation                          OperationName = "LoginPost"
	TaskGroupsGetOperation                      OperationName = "TaskGroupsGet"
	TaskGroupsGroupIdDeleteOperation            OperationName = "TaskGroupsGroupIdDelete"
	TaskGroupsGroupIdGetOperation               OperationName = "TaskGroupsGroupIdGet"
	TaskGroupsGroupIdTasksGetOperation          OperationName = "TaskGroupsGroupIdTasksGet"
	TaskGroupsGroupIdTasksPostOperation         OperationName = "TaskGroupsGroupIdTasksPost"
	TaskGroupsGroupIdUsersPostOperation         OperationName = "TaskGroupsGroupIdUsersPost"
	TaskGroupsGroupIdUsersUserIdDeleteOperation OperationName = "TaskGroupsGroupIdUsersUserIdDelete"
	TaskGroupsPostOperation                     OperationName = "TaskGroupsPost"
	TasksTaskIdDeleteOperation                  OperationName = "TasksTaskIdDelete"
	TasksTaskIdGetOperation                     OperationName = "TasksTaskIdGet"
	TasksTaskIdPutOperation                     OperationName = "TasksTaskIdPut"
	TasksTaskIdStatusPatchOperation             OperationName = "TasksTaskIdStatusPatch"
	UsersPostOperation                          OperationName = "UsersPost"
	UsersUserIdDeleteOperation                  OperationName = "UsersUserIdDelete"
)
