// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleJwtAuth handles jwtAuth security.
	HandleJwtAuth(ctx context.Context, operationName OperationName, t JwtAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesJwtAuth = map[string][]string{
	TaskGroupsGetOperation:                      []string{},
	TaskGroupsGroupIdDeleteOperation:            []string{},
	TaskGroupsGroupIdGetOperation:               []string{},
	TaskGroupsGroupIdTasksGetOperation:          []string{},
	TaskGroupsGroupIdTasksPostOperation:         []string{},
	TaskGroupsGroupIdUsersPostOperation:         []string{},
	TaskGroupsGroupIdUsersUserIdDeleteOperation: []string{},
	TaskGroupsPostOperation:                     []string{},
	TasksTaskIdDeleteOperation:                  []string{},
	TasksTaskIdGetOperation:                     []string{},
	TasksTaskIdPutOperation:                     []string{},
	TasksTaskIdStatusPatchOperation:             []string{},
	UsersUserIdDeleteOperation:                  []string{},
}

func (s *Server) securityJwtAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t JwtAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesJwtAuth[operationName]
	rctx, err := s.sec.HandleJwtAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// JwtAuth provides jwtAuth security value.
	JwtAuth(ctx context.Context, operationName OperationName) (JwtAuth, error)
}

func (s *Client) securityJwtAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.JwtAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"JwtAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
