// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LoginPost implements POST /login operation.
//
// ログイン.
//
// POST /login
func (UnimplementedHandler) LoginPost(ctx context.Context) (r *Token, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGroupsGet implements GET /task-groups operation.
//
// 所属グループ一覧取得.
//
// GET /task-groups
func (UnimplementedHandler) TaskGroupsGet(ctx context.Context) (r []TaskGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGroupsGroupIdDelete implements DELETE /task-groups/{groupId} operation.
//
// グループ削除.
//
// DELETE /task-groups/{groupId}
func (UnimplementedHandler) TaskGroupsGroupIdDelete(ctx context.Context, params TaskGroupsGroupIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// TaskGroupsGroupIdGet implements GET /task-groups/{groupId} operation.
//
// グループ詳細取得.
//
// GET /task-groups/{groupId}
func (UnimplementedHandler) TaskGroupsGroupIdGet(ctx context.Context, params TaskGroupsGroupIdGetParams) (r *TaskGroupDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGroupsGroupIdTasksGet implements GET /task-groups/{groupId}/tasks operation.
//
// タスク一覧取得.
//
// GET /task-groups/{groupId}/tasks
func (UnimplementedHandler) TaskGroupsGroupIdTasksGet(ctx context.Context, params TaskGroupsGroupIdTasksGetParams) (r []Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGroupsGroupIdTasksPost implements POST /task-groups/{groupId}/tasks operation.
//
// タスク作成.
//
// POST /task-groups/{groupId}/tasks
func (UnimplementedHandler) TaskGroupsGroupIdTasksPost(ctx context.Context, params TaskGroupsGroupIdTasksPostParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGroupsGroupIdUsersPost implements POST /task-groups/{groupId}/users operation.
//
// ユーザ招待.
//
// POST /task-groups/{groupId}/users
func (UnimplementedHandler) TaskGroupsGroupIdUsersPost(ctx context.Context, params TaskGroupsGroupIdUsersPostParams) (r *TaskGroupDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGroupsGroupIdUsersUserIdDelete implements DELETE /task-groups/{groupId}/users/{userId} operation.
//
// グループからユーザを削除.
//
// DELETE /task-groups/{groupId}/users/{userId}
func (UnimplementedHandler) TaskGroupsGroupIdUsersUserIdDelete(ctx context.Context, params TaskGroupsGroupIdUsersUserIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// TaskGroupsPost implements POST /task-groups operation.
//
// タスクグループ作成.
//
// POST /task-groups
func (UnimplementedHandler) TaskGroupsPost(ctx context.Context) (r *TaskGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksTaskIdDelete implements DELETE /tasks/{taskId} operation.
//
// タスク削除.
//
// DELETE /tasks/{taskId}
func (UnimplementedHandler) TasksTaskIdDelete(ctx context.Context, params TasksTaskIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// TasksTaskIdGet implements GET /tasks/{taskId} operation.
//
// タスク詳細取得.
//
// GET /tasks/{taskId}
func (UnimplementedHandler) TasksTaskIdGet(ctx context.Context, params TasksTaskIdGetParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksTaskIdPut implements PUT /tasks/{taskId} operation.
//
// タスク更新.
//
// PUT /tasks/{taskId}
func (UnimplementedHandler) TasksTaskIdPut(ctx context.Context, params TasksTaskIdPutParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksTaskIdStatusPatch implements PATCH /tasks/{taskId}/status operation.
//
// タスクステータス変更.
//
// PATCH /tasks/{taskId}/status
func (UnimplementedHandler) TasksTaskIdStatusPatch(ctx context.Context, params TasksTaskIdStatusPatchParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// ユーザ登録.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdDelete implements DELETE /users/{userId} operation.
//
// ユーザ削除.
//
// DELETE /users/{userId}
func (UnimplementedHandler) UsersUserIdDelete(ctx context.Context, params UsersUserIdDeleteParams) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
